[package]
name = "customasm"
version = "0.4.0"
authors = ["Henrique Lorenzi <hlorenzi12@gmail.com>"]

[lib]
name = "customasm"
path = "src/lib.rs"

[[bin]]
name = "customasm"
path = "src/main.rs"

[dependencies]
num-bigint = "0.1"